# docker-compose.yml
version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - ./logs:/app/logs
      - ./source:/app/source
      - ./config.yaml:/app/config.yaml
      - ./.env:/app/.env
      - ./db.sqlite3:/app/db.sqlite3
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - API_KEY=${API_KEY}
      - API_URL=${API_URL}
      - DB_NAME=database.db
      - BOT_USERNAME=${BOT_USERNAME}
      - BOT_NAME=${BOT_NAME}
      - BOT_LAST_NAME=${BOT_LAST_NAME}
      - BOT_TG_ID=${BOT_TG_ID}
      - OWNER_ID=${OWNER_ID}
      - DB_NAME=${DB_NAME}

    restart: unless-stopped